// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// TODO : REMOVE LATER
const SUPABASE_URL = 'https://dqlthucoxkixodoicksq.supabase.co';
const SUPABASE_PUBLISHABLE_KEY =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRxbHRodWNveGtpeG9kb2lja3NxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0NDIwMTAsImV4cCI6MjA3NjAxODAxMH0.Af5gSODhHqOmWlHwqindHlmv3Qe61MUzGLC60NRSr4A';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL ?? '',
  SUPABASE_PUBLISHABLE_KEY ?? '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
